### ISSUE TITLE
Simple Dunnos

### ISSUE THREAD

**Issue by inukaze** [IonicaBizau/memory-blocks#24]
Hi there i want to know if the game works in a web browser without internet connection ?
Or you can port to GNU/Linux native, this is because my mom love this game and Hangman for the Symantec Game Pack for Windows 3.1

And well i ever try to make it work with wine, but have constant screen flickering using from Wine 1.2 to actual version. and well i prefer hangman include spanish words

Thanks for readme.

**Comment by IonicaBizau** [comment]
Running the project locally should work just fine. ❇️
